version: '3.9'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@db:3306/movies
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdaten:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=movies
  
  tool:
    image: phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

volumes:
  dbdaten:
